### ISSUE TITLE
open : no such file or directory

### ISSUE THREAD

**Issue by melekhine** [Alienero/image2ascii#1]
When we try example on OSX, under Go 1.6 `go run image2ascii.go example/ex.png`

We have errors with our file opening.

```
panic: open : no such file or directory

goroutine 1 [running]:
panic(0x12cea0, 0xc820014300)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.main()
    /Users/Igor/Sites/GoCode/src/github.com/Alienero/image2ascii/image2ascii.go:56 +0x9b
exit status 2
```

If we try to hardcore path to out ex.png we have results.

**Comment by Alienero** [comment]
Using flag `path` to specify image's path.  
And `go run` will compile a binary file in the temporary directory.So this path is relative to the temporary directory.  
You can use `os.Getwd()` to get cmd's current directory or fist `go build` than `./image2ascii -path example/ex.png`

**Comment by Alienero** [comment]
close this issue
